# Generated by Django 4.2.5 on 2023-09-08 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('path', models.CharField(max_length=256)),
                ('format', models.CharField(max_length=32)),
                ('ifname', models.CharField(max_length=32)),
                ('hostname', models.CharField(max_length=64)),
                ('osvar', models.CharField(max_length=32)),
                ('config', models.JSONField(blank=True, default=dict, null=True)),
                ('meta_data_template', models.TextField()),
                ('user_data_template', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('value', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('workdir', models.CharField(max_length=256)),
                ('ip', models.GenericIPAddressField()),
                ('disk_size', models.IntegerField(default=100, verbose_name='Disk Size(GB)')),
                ('cpu', models.IntegerField(default=1, verbose_name='CPU')),
                ('mem', models.IntegerField(default=1, verbose_name='MEM(GB)')),
                ('config', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[], max_length=16)),
                ('stdout', models.TextField(blank=True, null=True)),
                ('base_img', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.baseimage')),
            ],
        ),
    ]
